jwt/extract.go, jwt/go.mod, rest/go.mod, rest/restid/restid.go
update aes import on jwt and rest
=> update aes import path

cdn/cdn.go
- change default width for cdn to 0
=> change default width to 0

rest/rest.go
=> feat: patch payload

rest/rest.go
- changed http request flow (from struct, through method)
- 1 function to handle various http methods
=> refactor: http request function

cache/cache.go, cache/connect.go, cache/go.mod
refactor: return error instead of directly logging
refactor: try to reconnect before error
refactor: added function name to error message
refactor: removed inaccurate "no such host" messages
=> refactor redis utils

logger/go.mod, logger/logger.go, rest/rest.go
- add Logger for User Activities (`LogUserActivity`)
- fix bug reading query param on MethodGet
=> Bug MethodGet & Logger User Activity

logger/go.mod, logger/logger.go
- fix import cycle (package `logger` & `rest`)
> manually Do request on the endpoint instead of using `request.Send()`
=> Fix Import Cycle

cache/cache.go, rest/restid/restid.go
helper function for forming redis key
=> feat: redis key helper

jwt/go.mod, rest/go.mod
update go mod for aes in other packages
=> update aes dependency

jwt/go.mod
=> update rest dependency in jwt

rest/rest.go
=> refactor: remove pointer

cache/key.go, rest/pagination/pagination.go
- clean up messy validations
- allow empty embedded struct
- remove field name when empty struct
- allow optional pagination
=> refactor redis key embedded struct

rest/go.mod
1. Updating AES version in go mod
=> fix: update aes

cache/key.go, middleware/auth.go
refactor: add detail to key error message
fix redis key for auth and check banned flow
added check suspend
=> fix: auth middleware

cache/cache.go, middleware/cors.go
refactor cache errors
GetUnmarshal return redis nil on empty cache
allow x-location-lat, x-location-long
=> refactor cache and allow location headers

elasticsearch/elasticsearch.go, logger/logger.go, middleware/auth.go, middleware/cors.go, middleware/interface.go, rest/request.go
- merge login redis
- add ai es
- refactor middleware to use interface
- minor refactor
=> refactor login

elasticsearch/elasticsearch.go
=> fix: ai elastic client

pagination/pagination.go, pagination/type.go
-  Granularized pagination functionality
-  add `TotalData` & `TotalPage` functionality
-  add maximum amount for limit
=> [go-utils/pagination] Granularized  pagination functionality & add total page

rest/entity.go, rest/rest.go
feat: integration API Activity
=> feat: integration API Activity

rest/entity.go, rest/rest.go
add new value to Request Struct
=> feat: add new value to Request Struct

go.mod, middleware/auth.go
- refactor whitelist checking from elasticsearch
- struct naming
- remove unused struct field
=> refactor: whitelist

middleware/auth.go
- log when redis is unreachable (instead of 500 response)
- added missing [mapstructure](https://github.com/mitchellh/mapstructure) struct tag
=> refactor: whitelist caching

v1/aes/aes.go
Task: [NYX-43](https://app.clickup.com/t/3857515/NYX-43)
- fix unhandled out of bound index when given parameter is invalid
=> [NYX-43] fix: aes.DecryptString

v1/rest/rest.go
=> remove unused package

v1/rest/rest.go
Task: [AI-52](https://app.clickup.com/t/3857515/AI-52)
- Add UTC time
=> [AI - 52] RabbitMQ Publisher in REST for Logging

v1/rest/responsestruct.go
Task: [COREAPI-285](https://app.clickup.com/t/3857515/COREAPI-285)
- Add error 423 Lock Response to response struct
- Add error 500 Internal server error to response struct
=> [COREAPI-285] Add Status Locked & Internal Server Error response struct

v1/middleware/auth.go
Task: [GIF-769](https://app.clickup.com/t/3857515/GIF-769)
- Add isSuspended function. This function is used for suspended checking a service
=> [GIF-769] Add suspend checking on middeware/auth

v1/middleware/auth.go
- refactor `IsSuspended` as `Middleware`'s method
=> [GIF-769] IsSuspended as method

v1/rest/rest.go
Task: [Update Response Structure on go-utils](https://app.clickup.com/t/3857515/COREAPI-352)
- `body` to `response`
- `ResponsePagination` helper function
=> [COREAPI-352] ResponsePagination, body -> result on response

v1/rest/bind.go, v1/rest/rest.go
Task: [COREAPI-355](https://app.clickup.com/t/3857515/COREAPI-355)
- request bind helper (json, urlencoded, form-data, multipart/form-data)
- minor refactor on `PublishLog()`
- `Content-Type: application/json`
<p align="center"><img src="https://user-images.githubusercontent.com/13652659/128738953-441955fe-e039-416a-a365-988b266f776c.png" width="400" /></p>
- `Content-Type: application/x-www-form-urlencoded`
<p align="center"><img src="https://user-images.githubusercontent.com/13652659/128739501-e5334b61-b78d-447c-a163-eed53d4241fc.png" width="400" /></p>
- `Content-Type: multipart/form-data` - no file
<p align="center"><img src="https://user-images.githubusercontent.com/13652659/128740203-fb029f3b-4087-46f3- …
=> [COREAPI-355] request bind helper

v1/middleware/auth.go
- remove whitelist checking to elastic
=> refactor: remove whitelist checking to elastic

v1/rabbitmq/connect.go, v1/rabbitmq/publisher/v1/exchange.go
> Please add your task in Clickup here.
Task: [AI-110](https://app.clickup.com/t/3857515/AI-110)
- Add `NotifyClose()` for RabbitMQ when connection and channel closed
=> [AI-110] Check RabbitMQ Error When Publishing in API

v1/rest/rest.go
=> Disable publish log

v1/aes/aes.go
Task: [DVM-97](https://app.clickup.com/t/3857515/DVM-97)
- add endpoint encrypt and decrypt for cms
=> [DVM-97] add endpoint encrypt and decrypt for cms

v1/aes/aes.go
Create new variables for cms encryption
Task: [DVM-1583](https://app.clickup.com/t/3857515/DVM-1583)
=> [DVM-1583] Fix aes cms encryption

v1/cache/cache.go, v1/cache/connect.go, v1/middleware/auth.go
enhancement
this `IsCacheConnected` function to PING the Redis take as long as 5s when it is **unable to reach**, which accumulate to 10s for the function `GetStatus` only. Thus this enhancement will reduce the time taken to get status by 5s.
=> fix: get banned status

v1/middleware/auth.go
Add Log when Redis Failed to Connect
=> Refactor: Add Log when Redis Failed to Connect

v1/aes/aes.go
- feat: decryptBulkCMS and encryptBulkCMS function
=> feat: decryptBulkCMS and encryptBulkCMS

v1/rest/rest.go
Task: [AI-330](https://app.clickup.com/t/3857515/AI-330)
- Use location in env
- Use unix timestamp
=> [AI-330] Use Unix Timestamp

v1/middleware/auth.go
Task: DVM-3095](https://app.clickup.com/t/3857515/DVM-3095)
- add new middleware option to check waiting status
=> [DVM-3095] Check Waiting Status

v1/middleware/interface.go
Task: DVM-3095](https://app.clickup.com/t/3857515/DVM-3095)
- add new middleware option to check waiting status (place function in interface)
=> [DVM-3095] add to interface

v1/rest/response/response.go, v1/rest/rest.go
- Add `[DEBUG]` line for ResponseError
- Publish Log to NSQ for ResponseError
- Using default status code message from IANA (check [here](https://cs.opensource.google/go/go/+/refs/tags/go1.17.7:src/net/http/status.go;l=150))
=> Add DEBUG log, NSQ publish, and using default message for each status code

v1/rest/rest.go
- Move DEBUG logs so existing message will get print if and only if status code is not 2xx
=> Move DEBUG logs

v1/middleware/auth.go
Task: [DVM-4202](https://app.clickup.com/t/3857515/DVM-4202)
- convert type string to type error so it can be used for other functions
=> [DVM-4202] Convert Type String to Type Error

go.mod, v1/aes/aes.go, v1/logger/logger.go, v1/middleware/auth.go, v1/rest/rest.go
Task: [DVM-5400](https://app.clickup.com/t/3857515/DVM-5400)
- Logger:
- Fatal
- Error
- Warn
- Info
- Debug
- Account Status Endpoint
- Rest Log
- Tidy go.mod
=> [DVM-5400] Logger; Account Status Endpoint; Rest Log

v1/logger/logger.go, v1/rest/rest.go
Task: [DVM-6722](https://app.clickup.com/t/3857515/DVM-6722)
- Log Error Handle Slice Interface
=> [HOTFIX] [DVM-6722] Log Error Handle Slice Interface

v1/middleware/auth.go
Task: [DVM-7653](https://app.clickup.com/t/3857515/DVM-7653)
- Centralized Access Token by checking to `[POST] v1/resource/check/token`
=> [DVM-7653] Centralized Access Token

v1/middleware/auth.go, v1/rest/rest.go
Task: [DVM-8278](https://app.clickup.com/t/3857515/DVM-8278)
- Log Handling when args is nil
- Better Auth Middleware Logging
=> [DVM-8278] Log Handling when args is nil; Auth Middleware Logging

v1/middleware/featureflagstatus.go, v1/middleware/interface.go
Task:  [DVM-8260](https://app.clickup.com/t/3857515/DVM-8260)
add CheckFeatureFlagStatus in middleware
=> [DVM-8260] Handle Server Down Time

v1/middleware/auth.go
Task: [DVM-9097](https://app.clickup.com/t/3857515/DVM-9097)
- separate checking for similar identity
=> [DVM-9097] Separate Checking for Similar Identity

v1/logger/logger.go
Task: -
- Logger Level Adjustment:
- Development/Staging/Production: Error level.
=> Logger Level Adjustment

v1/logger/logger.go
Task: -
- Log Request Even Without Context.
=> Log Request Even Without Context

v1/middleware/auth.go, v1/middleware/interface.go
Task: [DVM-14432](https://app.clickup.com/t/3857515/DVM-14432)
- New Middleware for Handling Guest Access 
Local test:
Without Auth:
With Auth:
=> [DVM-14432] Create New Middleware for Handling Guest Access

v1/aes/aes.go
- Fix function `EncryptString` and `DecryptString`
- Add function `EncryptStringBulk` and `DecryptStringBulk`
=> Fix Encrypt Decrypt String & Add Encrypt Decrypt String in Bulk

v1/rabbitmq/connect.go
- Separate RabbitMQ connection & channel are nil validation.
- Please handle RabbitMQ reconnection flow on each APIs.
- Log using go-utils package logger.
=> [DVM-14550] RabbitMQ Channel/Connection Enhancement

v1/rabbitmq/connect.go
- Logging RabbitMQ only when dialing connection or opening channel.
=> [DVM-14550] Logging RabbitMQ

v1/aes/aes.go
Refactor function `EncryptString` and `DecryptString` now always returning the same encryption value
=> Refactor Encrypt String Now Always Returning Constant Encryption Value

go.mod, v1/jwt/entity.go, v1/middleware/auth.go, v1/middleware/interface.go, v1/util/age/age.go
Add Middleware `AgeAuth`:
- AgeAuth will validates whether user already above the given minimum age or not.
Example: 
Task: [DVM-17723](https://app.clickup.com/t/3857515/DVM-17723)
=> [DVM-17723] Add Middleware `AgeAuth`

v1/jwt/constant.go, v1/jwt/entity.go, v1/jwt/extract.go, v1/middleware/auth.go
- remove unused UserClaims fields
- skip claims validation on JWT parser (remove time-related validation)
- checks token by jwt then by database
- enhance error logging
=> [DVM-21952] Enhancement Access Token

v1/jwt/extract.go
- SkipClaimsValidation become optional params with default value is true.
=> [DVM-22287] Handle Claims Expired Skip Validation
